name: Matthew Clement
favicon: null
layout_spectrum: 0.9971948303282261
typography_spectrum: 0.9476297721266747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0757581910584122
  lightness: 0.34583855071105063
  saturation: 0.28492685104720294
  rhythmicContrast: 0.2954044006764889
purpose: []
