typography_spectrum: 0.9476297721266747
content_rating:
  adult: false
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0757581910584122
  lightness: 0.34583855071105063
  saturation: 0.28492685104720294
  rhythmicContrast: 0.2954044006764889
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9971948303282261
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Matthew Clement
  email: matthew@matthewclement.com
name: Matthew Clement
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Matthew Clement
purpose: []
